name: Import New Episode

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  import-new-episode:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run import-new-episode
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add new episode"
          git push
          # npm run import-new-episode
